Fix for GCC alloc-size-larger-than warning
SacBase/Stdlib pull request #43
Opened 2020-12-07 13:48 UTC by hv15

This PR resolved bug #42.

2020-12-07 14:08 UTC, hv15 commented
Bugger, macos build fails because of `clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk' [-Wmissing-sysroot]`. Github updated the MacOS 10.15 image and changed to a newer version of XCode where the evidently the SDK is located somewhere else. Either sac2c needs to be recompiled or we need to update the `sac2crc` file. Ahhh.

2020-12-07 22:58 UTC, ashinkarov requested changes
Just use RuntimeError when you terminate compilation, other than that looks good to me.

2020-12-08 09:53 UTC, hv15 commented on src/stdio/src/ArrayIO/PrintArray.c
> +    exit (1);
done

2020-12-08 15:39 UTC, ashinkarov approved these changes

2020-12-08 15:40 UTC, merged